### ISSUE TITLE
Can't find the code of "Uncertainty-aware Mapping" mentioned in the paper

### ISSUE THREAD

**Issue by HerB1998** [MMRobotics/RSLO#1]
Thanks for the opensource code. But I can't find the code of "Uncertainty-aware Mapping" mentioned in the paper, I wonder if you have release it in this repository. Could you please tell me the location of this part.

**Comment by SamuelYale** [comment]
Dear HerB,
Thanks for your interest in our work. 
We temporarily have not released the mapping parts and might not have any recent plan on it considering the limited time budget.  
This part is involved in a complex framework and many code refactoring works are required. The core contribution of this work concentrates on the network part (which has been released). The mapping construction process is implemented as classic Bayesian filtering only to demonstrate the effectiveness of the learned point uncertainties.  
We encourage you to implement this part by yourself.  Thx.

Best regards,
Samuel
